M48
; DRILL file KiCad 10.0.3 date 2026-09-02T13:03:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-02T13:03:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X152.5Y-38.5
T2
X105.0Y-36.716
X105.0Y-126.716
X195.0Y-36.716
X195.0Y-126.716
M30
